# Generated by Django 3.0.7 on 2020-06-07 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200, verbose_name='название статьи')),
                ('post_text', models.TextField(verbose_name='текст статьи')),
                ('post_datetime', models.DateTimeField(verbose_name='дата публикации')),
                ('post_id', models.IntegerField(verbose_name='id и ссылка статьи')),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=50, verbose_name='автор комментария')),
                ('comment_text', models.CharField(max_length=200, verbose_name='текст статьи')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.NewsPost')),
            ],
        ),
    ]
